<div class="menu-bar">
    <a
        href="javascript:void(0);"
        class="btn"
        >Previous</a
    >
    <div class="sub-menu">
        <a
        href="javascript:void(0);"
        class="btn-small"
        >1</a
        >
        <a
        href="javascript:void(0);"
        class="btn-small"
        >2</a
        >
        <a
        href="javascript:void(0);"
        class="btn-small"
        >3</a
        >
        <a
        href="javascript:void(0);"
        class="btn-small"
        >4</a
        >
    </div>
    <a
        href="javascript:void(0);"
        class="btn"
        >Next</a
    >
</div>